# Generated by Django 5.1.1 on 2024-11-03 10:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financeManagment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryfinancemoviment",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="financemovements",
            name="billing_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Número Fatura"
            ),
        ),
        migrations.AlterField(
            model_name="financemovements",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="financeManagment.categoryfinancemoviment",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="financemovements",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="financemovements",
            name="file",
            field=models.FileField(
                upload_to="financeManager/None/", verbose_name="Ficheiro"
            ),
        ),
        migrations.AlterField(
            model_name="financemovements",
            name="value",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor",
            ),
        ),
    ]
