# Generated by Django 5.1.1 on 2024-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_school_scholl_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="scholl_year",
            field=models.CharField(
                choices=[
                    ("2024/2025", "2024/2025"),
                    ("2025/2026", "2025/2026"),
                    ("2026/2027", "2026/2027"),
                    ("2027/2028", "2027/2028"),
                    ("2028/2029", "2028/2029"),
                    ("2029/2030", "2029/2030"),
                    ("2030/2031", "2030/2031"),
                    ("2031/2032", "2031/2032"),
                    ("2032/2033", "2032/2033"),
                    ("2033/2034", "2033/2034"),
                ],
                default="2024/2025",
                max_length=9,
            ),
        ),
    ]
