# Generated by Django 5.1.1 on 2024-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="activity",
            field=models.ManyToManyField(null=True, to="school.activities"),
        ),
    ]
