# Generated by Django 5.1.1 on 2024-10-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_school_scholl_year"),
        ("student", "0002_alter_student_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="activity",
            field=models.ManyToManyField(blank=True, null=True, to="school.activities"),
        ),
    ]
