# Generated by Django 5.1.1 on 2024-11-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_alter_school_scholl_year"),
        ("student", "0003_alter_student_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlypayment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student",
                verbose_name="Estudante",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="activity",
            field=models.ManyToManyField(
                blank=True, to="school.activities", verbose_name="Atividade"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="education_officer",
            field=models.CharField(
                max_length=100, verbose_name="Nome Encarregado de educação"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="entry_year",
            field=models.IntegerField(verbose_name="Ano de Matrícula"),
        ),
        migrations.AlterField(
            model_name="student",
            name="fee",
            field=models.ManyToManyField(
                to="student.typefee", verbose_name="Mensalidade"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="student",
            name="out_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Ano de saída"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_numeber_officer",
            field=models.CharField(
                max_length=100, verbose_name="Contacto Enc Educação"
            ),
        ),
    ]
