# Generated by Django 5.1.1 on 2024-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "student",
            "0004_alter_monthlypayment_student_alter_student_activity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlypayment",
            name="value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
