# Generated by Django 5.1.1 on 2024-10-02 14:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableIRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tax", models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("security_system", models.FloatField(default=0.11)),
                (
                    "salary",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Saláro",
                    ),
                ),
                (
                    "hours",
                    models.IntegerField(
                        default=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas",
                    ),
                ),
                (
                    "duodecimos",
                    models.BooleanField(default=True, verbose_name="Duodécimos"),
                ),
                (
                    "contract",
                    models.FileField(
                        blank=True,
                        upload_to="employees/contract",
                        verbose_name="Contrato",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de início")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim do contrato"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.school",
                        verbose_name="Escola",
                    ),
                ),
                (
                    "Irs",
                    models.ManyToManyField(to="employees.tableirs", verbose_name="IRS"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de início")),
                ("end_date", models.DateField(verbose_name="Data fim")),
                (
                    "fouls",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
