# Generated by Django 5.1.1 on 2024-11-03 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="security_system",
            field=models.FloatField(default=0.11, verbose_name="Seg Social"),
        ),
        migrations.AlterField(
            model_name="employeesalary",
            name="fouls",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Falta em horas",
            ),
        ),
        migrations.AlterField(
            model_name="employeesalary",
            name="value",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor de Salário",
            ),
        ),
    ]
